#!/usr/bin/bash

# python3 proto.py empty

python3 proto.py cache \
    https://lava.sirena.org.uk/scheduler/job/179189/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179229/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179230/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179230/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179334/log_file/plain &

python3 proto.py cache \
    https://lava.sirena.org.uk/scheduler/job/179235/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179240/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179243/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179245/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179325/log_file/plain &

python3 proto.py cache \
    https://lava.sirena.org.uk/scheduler/job/179379/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179380/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179381/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179382/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179383/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179402/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179403/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179406/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179408/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179409/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179416/log_file/plain \
    https://lava.sirena.org.uk/scheduler/job/179427/log_file/plain &

wait
